In [1]:
# !pip install fastf1

In [2]:
import fastf1 as ff1
import fastf1.plotting

import numpy as np
import pandas as pd

In [3]:
# Enable the cache by providing the name of the cache folder
ff1.Cache.enable_cache('cache')

In [4]:
year= 2024
gp = 'Bahrain'
event = 'R'

In [5]:
session = ff1.get_session(year, gp, event)
session.load()
laps = session.laps

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.5.0]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']

In [6]:
session.laps

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:01:37.489000,VER,1,0 days 00:01:37.284000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:41.266000,...,False,Red Bull Racing,0 days 00:59:59.911000,2024-03-02 15:03:42.342,12,1.0,False,,False,False
1,0 days 01:03:13.785000,VER,1,0 days 00:01:36.296000,2.0,1.0,NaT,NaT,0 days 00:00:30.916000,0 days 00:00:41.661000,...,False,Red Bull Racing,0 days 01:01:37.489000,2024-03-02 15:05:19.920,1,1.0,False,,False,True
2,0 days 01:04:50.538000,VER,1,0 days 00:01:36.753000,3.0,1.0,NaT,NaT,0 days 00:00:30.999000,0 days 00:00:41.966000,...,False,Red Bull Racing,0 days 01:03:13.785000,2024-03-02 15:06:56.216,1,1.0,False,,False,True
3,0 days 01:06:27.185000,VER,1,0 days 00:01:36.647000,4.0,1.0,NaT,NaT,0 days 00:00:30.931000,0 days 00:00:41.892000,...,False,Red Bull Racing,0 days 01:04:50.538000,2024-03-02 15:08:32.969,1,1.0,False,,False,True
4,0 days 01:08:04.358000,VER,1,0 days 00:01:37.173000,5.0,1.0,NaT,NaT,0 days 00:00:31.255000,0 days 00:00:42.056000,...,False,Red Bull Racing,0 days 01:06:27.185000,2024-03-02 15:10:09.616,1,1.0,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1124,0 days 02:25:37.835000,SAR,2,0 days 00:01:35.972000,51.0,4.0,NaT,NaT,0 days 00:00:30.781000,0 days 00:00:41.539000,...,True,Williams,0 days 02:24:01.863000,2024-03-02 16:27:44.294,1,20.0,False,,False,True
1125,0 days 02:27:13.822000,SAR,2,0 days 00:01:35.987000,52.0,4.0,NaT,NaT,0 days 00:00:30.775000,0 days 00:00:41.440000,...,True,Williams,0 days 02:25:37.835000,2024-03-02 16:29:20.266,1,20.0,False,,False,True
1126,0 days 02:28:49.910000,SAR,2,0 days 00:01:36.088000,53.0,4.0,NaT,NaT,0 days 00:00:30.798000,0 days 00:00:41.610000,...,True,Williams,0 days 02:27:13.822000,2024-03-02 16:30:56.253,1,20.0,False,,False,True
1127,0 days 02:30:29.524000,SAR,2,0 days 00:01:39.614000,54.0,4.0,NaT,NaT,0 days 00:00:32.179000,0 days 00:00:43.748000,...,True,Williams,0 days 02:28:49.910000,2024-03-02 16:32:32.341,1,20.0,False,,False,True
1128,0 days 02:32:05.733000,SAR,2,0 days 00:01:36.209000,55.0,4.0,NaT,NaT,0 days 00:00:30.671000,0 days 00:00:41.782000,...,True,Williams,0 days 02:30:29.524000,2024-03-02 16:34:11.955,1,20.0,False,,False,True

In [7]:
session.event

RoundNumber                                                   1
Country                                                 Bahrain
Location                                                 Sakhir
OfficialEventName    FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2024
EventDate                                   2024-03-02 00:00:00
EventName                                    Bahrain Grand Prix
EventFormat                                        conventional
Session1                                             Practice 1
Session1Date                          2024-02-29 14:30:00+03:00
Session1DateUtc                             2024-02-29 11:30:00
Session2                                             Practice 2
Session2Date                          2024-02-29 18:00:00+03:00
Session2DateUtc                             2024-02-29 15:00:00
Session3                                             Practice 3
Session3Date                          2024-03-01 15:30:00+03:00
Session3DateUtc                             2024-03-01 12:30:00
Session4                                             Qualifying
Session4Date                          2024-03-01 19:00:00+03:00
Session4DateUtc                             2024-03-01 16:00:00
Session5                                                   Race
Session5Date                          2024-03-02 18:00:00+03:00
Session5DateUtc                             2024-03-02 15:00:00
F1ApiSupport                                               True
Name: 1, dtype: object

In [9]:
ff1.get_event_schedule(year)

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
0,0,Bahrain,Sakhir,FORMULA 1 ARAMCO PRE-SEASON TESTING 2024,2024-02-23,Pre-Season Testing,testing,Practice 1,2024-02-21 10:00:00+03:00,2024-02-21 07:00:00,...,Practice 3,2024-02-23 10:00:00+03:00,2024-02-23 07:00:00,None,NaT,NaT,None,NaT,NaT,True
1,1,Bahrain,Sakhir,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2024,2024-03-02,Bahrain Grand Prix,conventional,Practice 1,2024-02-29 14:30:00+03:00,2024-02-29 11:30:00,...,Practice 3,2024-03-01 15:30:00+03:00,2024-03-01 12:30:00,Qualifying,2024-03-01 19:00:00+03:00,2024-03-01 16:00:00,Race,2024-03-02 18:00:00+03:00,2024-03-02 15:00:00,True
2,2,Saudi Arabia,Jeddah,FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2024,2024-03-09,Saudi Arabian Grand Prix,conventional,Practice 1,2024-03-07 16:30:00+03:00,2024-03-07 13:30:00,...,Practice 3,2024-03-08 16:30:00+03:00,2024-03-08 13:30:00,Qualifying,2024-03-08 20:00:00+03:00,2024-03-08 17:00:00,Race,2024-03-09 20:00:00+03:00,2024-03-09 17:00:00,True
3,3,Australia,Melbourne,FORMULA 1 ROLEX AUSTRALIAN GRAND PRIX 2024,2024-03-24,Australian Grand Prix,conventional,Practice 1,2024-03-22 12:30:00+11:00,2024-03-22 01:30:00,...,Practice 3,2024-03-23 12:30:00+11:00,2024-03-23 01:30:00,Qualifying,2024-03-23 16:00:00+11:00,2024-03-23 05:00:00,Race,2024-03-24 15:00:00+11:00,2024-03-24 04:00:00,True
4,4,Japan,Suzuka,FORMULA 1 MSC CRUISES JAPANESE GRAND PRIX 2024,2024-04-07,Japanese Grand Prix,conventional,Practice 1,2024-04-05 11:30:00+09:00,2024-04-05 02:30:00,...,Practice 3,2024-04-06 11:30:00+09:00,2024-04-06 02:30:00,Qualifying,2024-04-06 15:00:00+09:00,2024-04-06 06:00:00,Race,2024-04-07 14:00:00+09:00,2024-04-07 05:00:00,True
5,5,China,Shanghai,FORMULA 1 LENOVO CHINESE GRAND PRIX 2024,2024-04-21,Chinese Grand Prix,sprint_qualifying,Practice 1,2024-04-19 11:30:00+08:00,2024-04-19 03:30:00,...,Sprint,2024-04-20 11:00:00+08:00,2024-04-20 03:00:00,Qualifying,2024-04-20 15:00:00+08:00,2024-04-20 07:00:00,Race,2024-04-21 15:00:00+08:00,2024-04-21 07:00:00,True
6,6,United States,Miami,FORMULA 1 CRYPTO.COM MIAMI GRAND PRIX 2024,2024-05-05,Miami Grand Prix,sprint_qualifying,Practice 1,2024-05-03 12:30:00-04:00,2024-05-03 16:30:00,...,Sprint,2024-05-04 12:00:00-04:00,2024-05-04 16:00:00,Qualifying,2024-05-04 16:00:00-04:00,2024-05-04 20:00:00,Race,2024-05-05 16:00:00-04:00,2024-05-05 20:00:00,True
7,7,Italy,Imola,FORMULA 1 MSC CRUISES GRAN PREMIO DEL MADE IN ...,2024-05-19,Emilia Romagna Grand Prix,conventional,Practice 1,2024-05-17 13:30:00+02:00,2024-05-17 11:30:00,...,Practice 3,2024-05-18 12:30:00+02:00,2024-05-18 10:30:00,Qualifying,2024-05-18 16:00:00+02:00,2024-05-18 14:00:00,Race,2024-05-19 15:00:00+02:00,2024-05-19 13:00:00,True
8,8,Monaco,Monaco,FORMULA 1 GRAND PRIX DE MONACO 2024,2024-05-26,Monaco Grand Prix,conventional,Practice 1,2024-05-24 13:30:00+02:00,2024-05-24 11:30:00,...,Practice 3,2024-05-25 12:30:00+02:00,2024-05-25 10:30:00,Qualifying,2024-05-25 16:00:00+02:00,2024-05-25 14:00:00,Race,2024-05-26 15:00:00+02:00,2024-05-26 13:00:00,True
9,9,Canada,Montréal,FORMULA 1 AWS GRAND PRIX DU CANADA 2024,2024-06-09,Canadian Grand Prix,conventional,Practice 1,2024-06-07 13:30:00-04:00,2024-06-07 17:30:00,...,Practice 3,2024-06-08 12:30:00-04:00,2024-06-08 16:30:00,Qualifying,2024-06-08 16:00:00-04:00,2024-06-08 20:00:00,Race,2024-06-09 14:00:00-04:00,2024-06-09 18:00:00,True
10,10,Spain,Barcelona,FORMULA 1 ARAMCO GRAN PREMIO DE ESPAÑA 2024,2024-06-23,Spanish Grand Prix,conventional,Practice 1,2024-06-21 13:30:00+02:00,2024-06-21 11:30:00,...,Practice 3,2024-06-22 12:30:00+02:00,2024-06-22 10:30:00,Qualifying,2024-06-22 16:00:00+02:00,2024-06-22 14:00:00,Race,2024-06-23 15:00:00+02:00,2024-06-23 13:00:00,True
11,11,Austria,Spielberg,FORMULA 1 QATAR AIRWAYS AUSTRIAN GRAND PRIX 2024,2024-06-30,Austrian Grand Prix,sprint_qualifying,Practice 1,2024-06-28 12:30:00+02:00,2024-06-28 10:30:00,...,Sprint,2024-06-29 12:00:00+02:00,2024-06-29 10:00:00,Qualifying,2024-06-29 16:00:00+02:00,2024-06-29 14:00:00,Race,2024-06-30 15:00:00+02:00,2024-06-30 13:00:00,True
12,12,United Kingdom,Silverstone,FORMULA 1 QATAR AIRWAYS BRITISH GRAND PRIX 2024,2024-07-07,British Grand Prix,conventional,Practice 1,2024-07-05 12:30:00+01:00,2024-07-05 11:30:00,...,Practice 3,2024-07-06 11:30:00+01:00,2024-07-06 10:30:00,Qualifying,2024-07-06 15:00:00+01:00,2024-07-06 14:00:00,Race,2024-07-07 15:00:00+01:00,2024-07-07 14:00:00,True
13,13,Hungary,Budapest,FORMULA 1 HUNGARIAN GRAND PRIX 2024,2024-07-21,Hungarian Grand Prix,conventional,Practice 1,2024-07-19 13:30:00+02:00,2024-07-19 11:30:00,...,Practice 3,2024-07-20 12:30:00+02:00,2024-07-20 10:30:00,Qualifying,2024-07-20 16:00:00+02:00,2024-07-20 14:00:00,Race,2024-07-21 15:00:00+02:00,2024-07-21 13:00:00,True
14,14,Belgium,Spa-Francorchamps,FORMULA 1 ROLEX BELGIAN GRAND PRIX 2024,2024-07-28,Belgian Grand Prix,conventional,Practice 1,2024-07-26 13:30:00+02:00,2024-07-26 11:30:00,...,Practice 3,2024-07-27 12:30:00+02:00,2024-07-27 10:30:00,Qualifying,2024-07-27 16:00:00+02:00,2024-07-27 14:00:00,Race,2024-07-28 15:00:00+02:00,2024-07-28 13:00:00,True
15,15,Netherlands,Zandvoort,FORMULA 1 HEINEKEN DUTCH GRAND PRIX 2024,2024-08-25,Dutch Grand Prix,conventional,Practice 1,2024-08-23 12:30:00+02:00,2024-08-23 10:30:00,...,Practice 3,2024-08-24 11:30:00+02:00,2024-08-24 09:30:00,Qualifying,2024-08-24 15:00:00+02:00,2024-08-24 13:00:00,Race,2024-08-25 15:00:00+02:00,2024-08-25 13:00:00,True
16,16,Italy,Monza,FORMULA 1 PIRELLI GRAN PREMIO D’ITALIA 2024,2024-09-01,Italian Grand Prix,conventional,Practice 1,2024-08-30 13:30:00+02:00,2024-08-30 11:30:00,...,Practice 3,2024-08-31 12:30:00+02:00,2024-08-31 10:30:00,Qualifying,2024-08-31 16:00:00+02:00,2024-08-31 14:00:00,Race,2024-09-01 15:00:00+02:00,2024-09-01 13:00:00,True
17,17,Azerbaijan,Baku,FORMULA 1 QATAR AIRWAYS AZERBAIJAN GRAND PRIX ...,2024-09-15,Azerbaijan Grand Prix,conventional,Practice 1,2024-09-13 13:30:00+04:00,2024-09-13 09:30:00,...,Practice 3,2024-09-14 12:30:00+04:00,2024-09-14 08:30:00,Qualifying,2024-09-14 16:00:00+04:00,2024-09-14 12:00:00,Race,2024-09-15 15:00:00+04:00,2024-09-15 11:00:00,True
18,18,Singapore,Marina Bay,FORMULA 1 SINGAPORE AIRLINES SINGAPORE GRAND P...,2024-09-22,Singapore Grand Prix,conventional,Practice 1,2024-09-20 17:30:00+08:00,2024-09-20 09:30:00,...,Practice 3,2024-09-21 17:30:00+08:00,2024-09-21 09:30:00,Qualifying,2024-09-21 21:00:00+08:00,2024-09-21 13:00:00,Race,2024-09-22 20:00:00+08:00,2024-09-22 12:00:00,True
19,19,United States,Austin,FORMULA 1 PIRELLI UNITED STATES GRAND PRIX 2024,2024-10-20,United States Grand Prix,sprint_qualifying,Practice 1,2024-10-18 12:30:00-05:00,2024-10-18 17:30:00,...,Sprint,2024-10-19 13:00:00-05:00,2024-10-19 18:00:00,Qualifying,2024-10-19 17:00:00-05:00,2024-10-19 22:00:00,Race,2024-10-20 14:00:00-05:00,2024-10-20 19:00:00,True
20,20,Mexico,Mexico City,FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2024,2024-10-27,Mexico City Grand Prix,conventional,Practice 1,2024-10-25 12:30:00-06:00,2024-10-25 18:30:00,...,Practice 3,2024-10-26 11:30:00-06:00,2024-10-26 17:30:00,Qualifying,2024-10-26 15:00:00-06:00,2024-10-26 21:00:00,Race,2024-10-27 14:00:00-06:00,2024-10-27 20:00:00,True
21,21,Brazil,São Paulo,FORMULA 1 LENOVO GRANDE PRÊMIO DE SÃO PAULO 2024,2024-11-03,São Paulo Grand Prix,sprint_qualifying,Practice 1,2024-11-01 11:30:00-03:00,2024-11-01 14:30:00,...,Sprint,2024-11-02 11:00:00-03:00,2024-11-02 14:00:00,Qualifying,2024-11-03 07:30:00-03:00,2024-11-03 10:30:00,Race,2024-11-03 12:30:00-03:00,2024-11-03 15:30:00,True
22,22,United States,Las Vegas,FORMULA 1 HEINEKEN SILVER LAS VEGAS GRAND PRIX...,2024-11-23,Las Vegas Grand Prix,conventional,Practice 1,2024-11-21 18:30:00-08:00,2024-11-22 02:30:00,...,Practice 3,2024-11-22 18:30:00-08:00,2024-11-23 02:30:00,Qualifying,2024-11-22 22:00:00-08:00,2024-11-23 06:00:00,Race,2024-11-23 22:00:00-08:00,2024-11-24 06:00:00,True
23,23,Qatar,Lusail,FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2024,2024-12-01,Qatar Grand Prix,sprint_qualifying,Practice 1,2024-11-29 16:30:00+03:00,2024-11-29 13:30:00,...,Sprint,2024-11-30 17:00:00+03:00,2024-11-30 14:00:00,Qualifying,2024-11-30 21:00:00+03:00,2024-11-30 18:00:00,Race,2024-12-01 19:00:00+03:00,2024-12-01 16:00:00,True
24,24,United Arab Emirates,Yas Island,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,2024-12-08,Abu Dhabi Grand Prix,conventional,Practice 1,2024-12-06 13:30:00+04:00,2024-12-06 09:30:00,...,Practice 3,2024-12-07 14:30:00+04:00,2024-12-07 10:30:00,Qualifying,2024-12-07 18:00:00+04:00,2024-12-07 14:00:00,Race,2024-12-08 17:00:00+04:00,2024-12-08 13:00:00,True

In [20]:
session.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671c6,red_bull,Max,Verstappen,Max Verstappen,...,NED,1.0,1,1.0,NaT,NaT,NaT,0 days 01:31:44.742000,Finished,26.0
11,11,S PEREZ,PER,perez,Red Bull Racing,3671c6,red_bull,Sergio,Perez,Sergio Perez,...,MEX,2.0,2,5.0,NaT,NaT,NaT,0 days 00:00:22.457000,Finished,18.0
55,55,C SAINZ,SAI,sainz,Ferrari,e8002d,ferrari,Carlos,Sainz,Carlos Sainz,...,ESP,3.0,3,4.0,NaT,NaT,NaT,0 days 00:00:25.110000,Finished,15.0
16,16,C LECLERC,LEC,leclerc,Ferrari,e8002d,ferrari,Charles,Leclerc,Charles Leclerc,...,MON,4.0,4,2.0,NaT,NaT,NaT,0 days 00:00:39.669000,Finished,12.0
63,63,G RUSSELL,RUS,russell,Mercedes,27f4d2,mercedes,George,Russell,George Russell,...,GBR,5.0,5,3.0,NaT,NaT,NaT,0 days 00:00:46.788000,Finished,10.0
4,4,L NORRIS,NOR,norris,McLaren,ff8000,mclaren,Lando,Norris,Lando Norris,...,GBR,6.0,6,7.0,NaT,NaT,NaT,0 days 00:00:48.458000,Finished,8.0
44,44,L HAMILTON,HAM,hamilton,Mercedes,27f4d2,mercedes,Lewis,Hamilton,Lewis Hamilton,...,GBR,7.0,7,9.0,NaT,NaT,NaT,0 days 00:00:50.324000,Finished,6.0
81,81,O PIASTRI,PIA,piastri,McLaren,ff8000,mclaren,Oscar,Piastri,Oscar Piastri,...,AUS,8.0,8,8.0,NaT,NaT,NaT,0 days 00:00:56.082000,Finished,4.0
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,ESP,9.0,9,6.0,NaT,NaT,NaT,0 days 00:01:14.887000,Finished,2.0
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,CAN,10.0,10,12.0,NaT,NaT,NaT,0 days 00:01:33.216000,Finished,1.0
24,24,G ZHOU,ZHO,zhou,Kick Sauber,52e252,sauber,Guanyu,Zhou,Guanyu Zhou,...,CHN,11.0,11,17.0,NaT,NaT,NaT,0 days 00:00:06.759000,+1 Lap,0.0
20,20,K MAGNUSSEN,MAG,kevin_magnussen,Haas F1 Team,b6babd,haas,Kevin,Magnussen,Kevin Magnussen,...,DEN,12.0,12,15.0,NaT,NaT,NaT,0 days 00:00:08.316000,+1 Lap,0.0
3,3,D RICCIARDO,RIC,ricciardo,RB,6692ff,rb,Daniel,Ricciardo,Daniel Ricciardo,...,AUS,13.0,13,14.0,NaT,NaT,NaT,0 days 00:00:08.958000,+1 Lap,0.0
22,22,Y TSUNODA,TSU,tsunoda,RB,6692ff,rb,Yuki,Tsunoda,Yuki Tsunoda,...,JPN,14.0,14,11.0,NaT,NaT,NaT,0 days 00:00:09.482000,+1 Lap,0.0
23,23,A ALBON,ALB,albon,Williams,64c4ff,williams,Alexander,Albon,Alexander Albon,...,THA,15.0,15,13.0,NaT,NaT,NaT,0 days 00:00:11.886000,+1 Lap,0.0
27,27,N HULKENBERG,HUL,hulkenberg,Haas F1 Team,b6babd,haas,Nico,Hulkenberg,Nico Hulkenberg,...,GER,16.0,16,10.0,NaT,NaT,NaT,0 days 00:00:17.632000,+1 Lap,0.0
31,31,E OCON,OCO,ocon,Alpine,ff87bc,alpine,Esteban,Ocon,Esteban Ocon,...,FRA,17.0,17,19.0,NaT,NaT,NaT,0 days 00:00:31.450000,+1 Lap,0.0
10,10,P GASLY,GAS,gasly,Alpine,ff87bc,alpine,Pierre,Gasly,Pierre Gasly,...,FRA,18.0,18,20.0,NaT,NaT,NaT,0 days 00:00:32.417000,+1 Lap,0.0
77,77,V BOTTAS,BOT,bottas,Kick Sauber,52e252,sauber,Valtteri,Bottas,Valtteri Bottas,...,FIN,19.0,19,16.0,NaT,NaT,NaT,0 days 00:01:23.230000,+1 Lap,0.0
2,2,L SARGEANT,SAR,sargeant,Williams,64c4ff,williams,Logan,Sargeant,Logan Sargeant,...,USA,20.0,20,18.0,NaT,NaT,NaT,0 days 00:00:20.795000,+2 Laps,0.0

In [21]:
session.track_status

                    Time Status   Message
0 0 days 00:10:06.010000      1  AllClear
1 0 days 01:00:16.400000      2    Yellow
2 0 days 01:00:20.890000      1  AllClear
3 0 days 01:00:46.461000      2    Yellow
4 0 days 01:00:53.481000      1  AllClear
5 0 days 01:15:24.819000      2    Yellow
6 0 days 01:16:15.962000      1  AllClear

In [22]:
session.session_status

                    Time     Status
0 0 days 00:00:09.193000   Inactive
1 0 days 00:59:59.911000    Started
2 0 days 02:31:44.878000   Finished
3 0 days 02:36:15.245000  Finalised
4 0 days 02:36:15.245000       Ends

In [23]:
session.race_control_messages

,Time,Category,Message,Status,Flag,Scope,Sector,RacingNumber,Lap
0,2024-03-02 14:06:41,Other,PINK HEAD PADDING MATERIAL MUST BE USED,None,None,None,NaN,None,1
1,2024-03-02 14:20:01,Flag,GREEN LIGHT - PIT EXIT OPEN,None,GREEN,Track,NaN,None,1
2,2024-03-02 14:30:01,Other,PIT EXIT CLOSED,None,None,None,NaN,None,1
3,2024-03-02 14:45:29,Other,RISK OF RAIN FOR F1 RACE IS 0%,None,None,None,NaN,None,1
4,2024-03-02 14:57:04,Drs,DRS DISABLED,DISABLED,None,None,NaN,None,1
...,...,...,...,...,...,...,...,...,...
64,2024-03-02 16:34:28,Other,CAR 10 (GAS) TIME 1:35.908 DELETED - TRACK LIM...,None,None,None,NaN,None,57
65,2024-03-02 16:35:26,Flag,CHEQUERED FLAG,None,CHEQUERED,Track,NaN,None,57
66,2024-03-02 16:35:53,Other,CAR 3 (RIC) TIME 1:37.662 DELETED - TRACK LIMI...,None,None,None,NaN,None,57
67,2024-03-02 16:36:01,Flag,BLACK AND WHITE FLAG FOR CAR 3 (RIC) - TRACK L...,None,BLACK AND WHITE,Driver,NaN,3,57
68,2024-03-02 16:38:38,Other,CAR 4 (NOR) TIME 1:35.976 DELETED - TRACK LIMI...,None,None,None,NaN,None,57

In [27]:
session.laps.pick_fastest().get_car_data()

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
0,2024-03-02 16:05:28.521,11259.0,285.0,7,100.0,False,0,car,0 days 00:00:00.154000,0 days 02:01:46.090000
1,2024-03-02 16:05:28.801,11353.0,286.0,7,100.0,False,0,car,0 days 00:00:00.434000,0 days 02:01:46.370000
2,2024-03-02 16:05:28.961,11357.0,287.0,7,100.0,False,0,car,0 days 00:00:00.594000,0 days 02:01:46.530000
3,2024-03-02 16:05:29.161,11406.0,289.0,7,100.0,False,0,car,0 days 00:00:00.794000,0 days 02:01:46.730000
4,2024-03-02 16:05:29.601,11489.0,291.0,7,100.0,False,0,car,0 days 00:00:01.234000,0 days 02:01:47.170000
...,...,...,...,...,...,...,...,...,...,...
344,2024-03-02 16:06:59.881,10991.0,275.0,7,100.0,False,0,car,0 days 00:01:31.514000,0 days 02:03:17.450000
345,2024-03-02 16:07:00.201,11056.0,278.0,7,100.0,False,0,car,0 days 00:01:31.834000,0 days 02:03:17.770000
346,2024-03-02 16:07:00.361,11124.0,279.0,7,100.0,False,0,car,0 days 00:01:31.994000,0 days 02:03:17.930000
347,2024-03-02 16:07:00.521,11140.0,281.0,7,100.0,False,0,car,0 days 00:01:32.154000,0 days 02:03:18.090000
348,2024-03-02 16:07:00.881,11234.0,283.0,7,100.0,False,0,car,0 days 00:01:32.514000,0 days 02:03:18.450000

In [28]:
session.weather_data

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:14.093000,18.9,46.0,1017.1,False,26.5,162,0.9
1,0 days 00:01:14.084000,18.9,46.0,1017.0,False,26.5,55,1.0
2,0 days 00:02:14.093000,18.9,46.0,1017.0,False,26.5,55,1.0
3,0 days 00:03:14.090000,18.9,45.0,1017.0,False,26.2,85,1.1
4,0 days 00:04:14.091000,18.9,46.0,1017.0,False,26.2,178,1.0
...,...,...,...,...,...,...,...,...
152,0 days 02:32:14.300000,17.6,51.0,1017.5,False,21.9,0,0.7
153,0 days 02:33:14.300000,17.6,51.0,1017.5,False,21.9,271,0.0
154,0 days 02:34:14.313000,17.7,51.0,1017.5,False,21.9,0,0.4
155,0 days 02:35:14.305000,17.6,51.0,1017.5,False,21.9,257,0.0
156,0 days 02:36:14.319000,17.7,51.0,1017.4,False,21.9,167,0.0

In [ ]:
drivers = session.drivers
print(drivers)

In [ ]:
drivers = [session.get_driver(driver)["Abbreviation"] for driver in drivers]
print(drivers)

In [ ]:
stints = laps[["Driver", "Stint", "Compound", "LapNumber"]]
stints = stints.groupby(["Driver", "Stint", "Compound"])
stints = stints.count().reset_index()

In [ ]:
stints = stints.rename(columns={"LapNumber": "StintLength"})
print(stints)

In [ ]:
fig, ax = plt.subplots(figsize=(5, 10))

for driver in drivers:
    driver_stints = stints.loc[stints["Driver"] == driver]

    previous_stint_end = 0
    for idx, row in driver_stints.iterrows():
        # each row contains the compound name and stint length
        # we can use these information to draw horizontal bars
        compound_color = fastf1.plotting.get_compound_color(row["Compound"],
                                                            session=session)
        plt.barh(
            y=driver,
            width=row["StintLength"],
            left=previous_stint_end,
            color=compound_color,
            edgecolor="black",
            fill=True
        )

        previous_stint_end += row["StintLength"]

plt.title("2023 Bahrain Grand Prix Strategies")
plt.xlabel("Lap Number")
plt.grid(False)
# invert the y-axis so drivers that finish higher are closer to the top
ax.invert_yaxis()

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_visible(False)

plt.tight_layout()
plt.show()

In [ ]:
session_event.laps